export type Permission = {
  code: string;
  module: string;
  description: string;
};

export const PERMISSIONS: Permission[] = [
  { code: "dashboard.view", module: "Dashboard", description: "View the operational dashboard" },
  { code: "dashboard.financial", module: "Dashboard", description: "View financial figures on the dashboard" },
  { code: "patients.view", module: "Patients", description: "View patient records" },
  { code: "patients.view_contact", module: "Patients", description: "View full contact numbers and addresses" },
  { code: "patients.view_sensitive", module: "Patients", description: "View allergies and medical history" },
  { code: "patients.create", module: "Patients", description: "Register patients" },
  { code: "patients.edit", module: "Patients", description: "Edit patient demographics" },
  { code: "patients.archive", module: "Patients", description: "Archive patients" },
  { code: "patients.export", module: "Patients", description: "Export patient lists" },
  { code: "appointments.view", module: "Appointments", description: "View appointments" },
  { code: "appointments.create", module: "Appointments", description: "Create appointments" },
  { code: "appointments.edit", module: "Appointments", description: "Edit, reschedule, or cancel appointments" },
  { code: "queue.view", module: "Queue", description: "View the patient queue" },
  { code: "queue.manage", module: "Queue", description: "Update queue status and priority" },
  { code: "nurse.view", module: "Nurse Station", description: "View triage and vital signs" },
  { code: "nurse.create", module: "Nurse Station", description: "Record nurse encounters" },
  { code: "clinical.view", module: "Doctors", description: "View clinical consultations" },
  { code: "clinical.create", module: "Doctors", description: "Create clinical consultations" },
  { code: "clinical.edit", module: "Doctors", description: "Correct clinical consultations" },
  { code: "psychology.view", module: "Psychology", description: "View psychology sessions" },
  { code: "psychology.create", module: "Psychology", description: "Create psychology sessions" },
  { code: "psychology.edit", module: "Psychology", description: "Correct psychology sessions" },
  { code: "prescriptions.view", module: "Prescriptions", description: "View prescriptions" },
  { code: "prescriptions.create", module: "Prescriptions", description: "Create prescriptions" },
  { code: "prescriptions.dispense", module: "Pharmacy", description: "Dispense medicines" },
  { code: "billing.view", module: "Billing", description: "View invoices and balances" },
  { code: "billing.create", module: "Billing", description: "Create invoices" },
  { code: "billing.edit", module: "Billing", description: "Edit unpaid invoice charges" },
  { code: "billing.void", module: "Billing", description: "Void invoices" },
  { code: "payments.create", module: "Payments", description: "Record payments and issue receipts" },
  { code: "payments.reverse", module: "Payments", description: "Reverse payments" },
  { code: "receipts.view", module: "Receipts", description: "View and print receipts" },
  { code: "inventory.view", module: "Inventory", description: "View medicines and stock" },
  { code: "inventory.create", module: "Inventory", description: "Add medicines and receive stock" },
  { code: "inventory.adjust", module: "Inventory", description: "Adjust, damage, or write off stock" },
  { code: "expenses.view", module: "Expenses", description: "View expenses" },
  { code: "expenses.create", module: "Expenses", description: "Record expenses" },
  { code: "expenses.void", module: "Expenses", description: "Void expenses" },
  { code: "reports.view", module: "Reports", description: "View operational reports" },
  { code: "reports.clinical", module: "Reports", description: "View clinical reports" },
  { code: "reports.financial", module: "Reports", description: "View financial reports" },
  { code: "reports.export", module: "Reports", description: "Export reports" },
  { code: "documents.view", module: "Documents", description: "View patient documents" },
  { code: "documents.upload", module: "Documents", description: "Upload and archive documents" },
  { code: "users.manage", module: "Users", description: "Manage users, roles, and access" },
  { code: "audit.view", module: "Audit", description: "View the audit log" },
  { code: "settings.manage", module: "Settings", description: "Manage clinic settings and reference lists" },
  { code: "doctors.view", module: "Doctors", description: "View doctor information" },
  { code: "doctors.manage", module: "Doctors", description: "Edit doctor information" },
  { code: "import.manage", module: "Import", description: "Import historical data" },
  { code: "notifications.view", module: "Notifications", description: "View notifications" },
  { code: "override.emergency", module: "Security", description: "Record a reasoned emergency access override" },
];

export const ALL_PERMISSION_CODES = PERMISSIONS.map((item) => item.code);

const clinicalRead = [
  "dashboard.view",
  "patients.view",
  "patients.view_contact",
  "patients.view_sensitive",
  "appointments.view",
  "queue.view",
  "notifications.view",
  "documents.view",
];

export const ROLE_SEEDS: { code: string; name: string; description: string; permissions: string[] }[] = [
  {
    code: "administrator",
    name: "Administrator",
    description: "Full clinic administration",
    permissions: ALL_PERMISSION_CODES,
  },
  {
    code: "doctor",
    name: "Doctor",
    description: "Clinical consultation and prescriptions",
    permissions: [
      ...clinicalRead,
      "patients.create",
      "patients.edit",
      "appointments.create",
      "appointments.edit",
      "queue.manage",
      "nurse.view",
      "clinical.view",
      "clinical.create",
      "clinical.edit",
      "psychology.view",
      "prescriptions.view",
      "prescriptions.create",
      "documents.upload",
      "reports.view",
      "reports.clinical",
      "doctors.view",
    ],
  },
  {
    code: "nurse",
    name: "Nurse",
    description: "Triage, vitals, and queue support",
    permissions: [
      ...clinicalRead,
      "queue.manage",
      "nurse.view",
      "nurse.create",
      "prescriptions.view",
      "clinical.view",
    ],
  },
  {
    code: "receptionist",
    name: "Receptionist",
    description: "Registration, appointments, queue, and front-desk billing",
    permissions: [
      "dashboard.view",
      "patients.view",
      "patients.view_contact",
      "patients.create",
      "patients.edit",
      "appointments.view",
      "appointments.create",
      "appointments.edit",
      "queue.view",
      "queue.manage",
      "billing.view",
      "billing.create",
      "payments.create",
      "receipts.view",
      "documents.view",
      "documents.upload",
      "doctors.view",
      "notifications.view",
      "reports.view",
    ],
  },
  {
    code: "psychologist",
    name: "Psychologist",
    description: "Mental health sessions and longitudinal notes",
    permissions: [
      ...clinicalRead,
      "appointments.create",
      "queue.manage",
      "psychology.view",
      "psychology.create",
      "psychology.edit",
      "clinical.view",
      "prescriptions.view",
      "documents.upload",
      "reports.view",
      "reports.clinical",
    ],
  },
  {
    code: "pharmacist",
    name: "Pharmacist",
    description: "Dispensing and drug inventory",
    permissions: [
      "dashboard.view",
      "patients.view",
      "prescriptions.view",
      "prescriptions.dispense",
      "inventory.view",
      "inventory.create",
      "inventory.adjust",
      "queue.view",
      "billing.view",
      "billing.create",
      "notifications.view",
      "reports.view",
    ],
  },
  {
    code: "accountant",
    name: "Accountant",
    description: "Billing, receipts, expenses, and financial reports",
    permissions: [
      "dashboard.view",
      "dashboard.financial",
      "patients.view",
      "patients.view_contact",
      "billing.view",
      "billing.create",
      "billing.edit",
      "billing.void",
      "payments.create",
      "payments.reverse",
      "receipts.view",
      "expenses.view",
      "expenses.create",
      "expenses.void",
      "reports.view",
      "reports.financial",
      "reports.export",
      "notifications.view",
    ],
  },
  {
    code: "manager",
    name: "Manager",
    description: "Operational and financial oversight without clinical editing",
    permissions: [
      "dashboard.view",
      "dashboard.financial",
      "patients.view",
      "patients.view_contact",
      "appointments.view",
      "queue.view",
      "inventory.view",
      "billing.view",
      "receipts.view",
      "expenses.view",
      "reports.view",
      "reports.financial",
      "reports.export",
      "doctors.view",
      "audit.view",
      "notifications.view",
    ],
  },
  {
    code: "it_admin",
    name: "IT / System Administrator",
    description: "Users, settings, audit, and imports without routine clinical access",
    permissions: [
      "dashboard.view",
      "users.manage",
      "settings.manage",
      "audit.view",
      "import.manage",
      "doctors.view",
      "doctors.manage",
      "notifications.view",
    ],
  },
];

export const NAV_ITEMS: { href: string; label: string; perm: string; group: string }[] = [
  { href: "/dashboard", label: "Dashboard", perm: "dashboard.view", group: "Overview" },
  { href: "/patients", label: "Patients", perm: "patients.view", group: "Care" },
  { href: "/appointments", label: "Appointments", perm: "appointments.view", group: "Care" },
  { href: "/queue", label: "Queue", perm: "queue.view", group: "Care" },
  { href: "/nurse", label: "Nurse Station", perm: "nurse.view", group: "Clinical" },
  { href: "/doctors", label: "Doctors", perm: "clinical.view", group: "Clinical" },
  { href: "/psychology", label: "Psychologist", perm: "psychology.view", group: "Clinical" },
  { href: "/inventory", label: "Drug Inventory", perm: "inventory.view", group: "Pharmacy" },
  { href: "/billing", label: "Billing", perm: "billing.view", group: "Finance" },
  { href: "/receipts", label: "Receipts", perm: "receipts.view", group: "Finance" },
  { href: "/expenses", label: "Expenses", perm: "expenses.view", group: "Finance" },
  { href: "/finance", label: "Financial Reports", perm: "reports.financial", group: "Finance" },
  { href: "/reports", label: "Clinical Reports", perm: "reports.view", group: "Records" },
  { href: "/documents", label: "Documents", perm: "documents.view", group: "Records" },
  { href: "/doctors-info", label: "Doctors Information", perm: "doctors.view", group: "Administration" },
  { href: "/users", label: "Users & Staff", perm: "users.manage", group: "Administration" },
  { href: "/audit", label: "Audit Logs", perm: "audit.view", group: "Administration" },
  { href: "/settings", label: "Settings", perm: "settings.manage", group: "Administration" },
  { href: "/help", label: "Help", perm: "dashboard.view", group: "Administration" },
];

export const ROUTE_GUARDS: { prefix: string; perm: string }[] = [
  { prefix: "/settings", perm: "settings.manage" },
  { prefix: "/audit", perm: "audit.view" },
  { prefix: "/users", perm: "users.manage" },
  { prefix: "/doctors-info", perm: "doctors.view" },
  { prefix: "/documents", perm: "documents.view" },
  { prefix: "/reports", perm: "reports.view" },
  { prefix: "/finance", perm: "reports.financial" },
  { prefix: "/expenses", perm: "expenses.view" },
  { prefix: "/receipts", perm: "receipts.view" },
  { prefix: "/billing", perm: "billing.view" },
  { prefix: "/inventory", perm: "inventory.view" },
  { prefix: "/psychology", perm: "psychology.view" },
  { prefix: "/doctors", perm: "clinical.view" },
  { prefix: "/nurse", perm: "nurse.view" },
  { prefix: "/queue", perm: "queue.view" },
  { prefix: "/appointments", perm: "appointments.view" },
  { prefix: "/patients", perm: "patients.view" },
  { prefix: "/dashboard", perm: "dashboard.view" },
  { prefix: "/help", perm: "dashboard.view" },
];

export function canAccess(permissions: string[], code: string) {
  return permissions.includes("*") || permissions.includes(code);
}
